= Memory Image Pattern
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::partial$include.adoc[]


Memory Image is a programming pattern in which data stored on the database is resides in memory. This means data access doesn't require a round-trip to the database. As a consequence, the application code is responsible for:

1. handling concurrent modification attempts, and 
2. keeping the consistency across nodes running the application.

== Sharded Singletons

One way to meet the two requirements above is to ensure only one copy of the data is on memory at any given time. Then, because your data may exceed the capacity of your memory, you can shard the data and keep a chunk on each of your application nodes. Finally, each shard of data uses mutual exclusion mechanisms to ensure each mutation happens serially.

{akka}/typed/actors.html#akka-actors[Akka actors] {akka}/typed/actors.html#akka-actors[{tab-icon}, window="tab"] provide serial access to mutating data out of the box. If an actor, is a direct image of some persistent data it becomes a memory image. Finally, Akka Cluster provides the means to implement the "Sharded Singletons" approach by {akka}/typed/cluster-sharding.html[sharding] {akka}/typed/cluster-sharding.html[{tab-icon}, window="tab"] all your actors.

The xref:microservices-tutorial:index.adoc[Implementing Microservices with Akka] tutorial teaches how to create a microservice that uses xref:event-sourcing.adoc[Event Sourced] persistent sharded actors.

== Replicated Images

The Sharded Singletons approach to Memory Image prefers https://en.wikipedia.org/wiki/CAP_theorem[Consistency to Availability]. You may decrease the Consistency guarantees in favor of Availability if you implement your memory images in a way that concurrent mutation may converge.

Akka Persistence supports Replicated Images for Event Sourced actors in the {akka}/typed/replicated-eventsourcing.html#relaxing-the-single-writer-principle-for-availability[Replicated Event Sourcing API] {akka}/typed/replicated-eventsourcing.html#relaxing-the-single-writer-principle-for-availability[{tab-icon}, window="tab"].


Learn more about the Memory Image pattern at https://www.martinfowler.com/bliki/MemoryImage.html[Martin Fowler's bliki post].